### ISSUE TITLE
query id already hidden

### ISSUE THREAD

**Issue by celiaraish** [Solana0x/NotPixel#10]
what know? can u give login by tga-auth-token?

**Comment by Solana0x** [comment]
Login via Tg-auth token is very very risky for a telegram account and very high chances of getting banned ! via tg so i would recommended  either use this method or else dont do bot ! risky whole account for just one bot doesnt sounds good!

**Comment by jerrydao** [comment]
I agree. Never use any bot that ask for AUTH Token. query ID or user ID is the best....

**Comment by Solana0x** [comment]
yeah

**Comment by celiaraish** [comment]
> Login via Tg-auth token is very very risky for a telegram account and very high chances of getting banned ! via tg so i would recommended either use this method or else dont do bot ! risky whole account for just one bot doesnt sounds good!

ohh, thanks for help im new with all method. My bad for not learn more
