### ISSUE TITLE
Failed to fetch mining data error: 401

### ISSUE THREAD

**Issue by danazor** [Solana0x/NotPixel#11]
Hey there! Im totally noob and sorry if i boring you with my error.

I copied tgWebAppData link like user=%7B%22id%22%3xxxxxxxx%2C%22first_name%22%3A%22.......... and than paste to data.txt Quer id
it looks
Quer_id=user=%7B%22id%22%3xxxxxxxx%2C%22first_name%22%3A%22..........
user=my username

and get "Failed to fetch mining data error: 401"
Dead :(

what am i missing? can you help me please?
![2908736e-895a-4224-b723-dd8c3bc9d517](https://github.com/user-attachments/assets/39e70ce8-f7d8-452f-bf68-01b81ca2fb18)

**Comment by Solana0x** [comment]
thats means Query id is expired

**Comment by danazor** [comment]
> thats means Query id is expired

Thanks for your reply. Is there a way to fix this issue?

**Comment by Solana0x** [comment]
generate another Query id

**Comment by danazor** [comment]
> generate another Query id

I don't know how to create it but I will look into it and try it out thanks!
