### ISSUE TITLE
Please enter your phone (or bot token):

### ISSUE THREAD

**Issue by Mostaphadartagnan** [Solana0x/NotPixel#12]
I put the bot token in nano data.txt , and it ask me again and put it also put the phone number  ,but it keep asking the same question!! ![Screenshot_2024-09-28-00-24-33-21_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/b7ef806f-817b-4dab-81d9-3c0f665c27a3)

**Comment by Solana0x** [comment]
this is not my bot script

**Comment by callousedparagon** [comment]
NotPixel has Query ID regeneration problem ?
