### ISSUE TITLE
query id problem

### ISSUE THREAD

**Issue by amirnajm** [Solana0x/NotPixel#15]
hello sir i want to use this code but cant get query id for notpixel, i did what you said in post but for "query_id=     ' is missing and i just get 'user=         ' should i use this for query id? i get this id for blum easily but for notpixel i cant. can you help me?

**Comment by siddiq56** [comment]
Same here

**Comment by Solana0x** [comment]
You can either use Query=

or you can use user=

please use what ever you got from the bot some people gets Query id some gets user id !
