### ISSUE TITLE
Failed to fetch mining data 401

### ISSUE THREAD

**Issue by 5H4K1L** [Solana0x/NotPixel#19]
After first run, it show every time, even it say to wait for 1 hour, after that it still showing the error

**Comment by Solana0x** [comment]
Query id Expires after an hr

**Comment by 5H4K1L** [comment]
But in other game bot query not expired, any fix for notpixel bot?

**Comment by batreller** [comment]
you need to use telethon / pyrogram to imitate you click to the button that opens the game and it will return you all of these params
the way it is made in this repository is really weird
