### ISSUE TITLE
Can't get a session

### ISSUE THREAD

**Issue by arbuziksp** [Solana0x/NotPixel#2]
![image](https://github.com/user-attachments/assets/c5ea53fe-707a-4c89-b834-b12c95101448)

**Comment by Solana0x** [comment]
dont get by this way !

try going this way 

![image](https://github.com/user-attachments/assets/d2a7362b-14eb-40e1-a365-c5e96d434645)

**Comment by Solana0x** [comment]
Try this way !

![image](https://github.com/user-attachments/assets/b2bc7256-4a08-4e8c-8bcd-e7a4032a9d71)
