### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Minecryp** [Solana0x/NotPixel#4]
![Screenshot_20240925-184116_Termux](https://github.com/user-attachments/assets/828af5c8-dbfc-4370-98d9-a2018ecca832)
![Screenshot_20240925-184125_Termux](https://github.com/user-attachments/assets/745bbf32-e1e5-4742-b75c-d43136509b52)

After I enter "pip install -r requirements.txt" this is what happened. How do I fix this? Please help

**Comment by Solana0x** [comment]
Install Python i guess you are using Termux ?

**Comment by Minecryp** [comment]
Yes, I'm using Termux. I already installed Python.

Edit: I found a way to install it. Thanks for the repository.

**Comment by Solana0x** [comment]
ok
