### ISSUE TITLE
return null

### ISSUE THREAD

**Issue by mahdi429** [Solana0x/NotPixel#7]
sessionStorage.getItem('query_id')  return  null

**Comment by Solana0x** [comment]
use this 

![image](https://github.com/user-attachments/assets/a0108d54-50e8-4b84-82c1-4aee4ea1f9a6)

**Comment by mahdi429** [comment]
ACCOUNT: Unknown 
![Screenshot 2024-09-25 220149](https://github.com/user-attachments/assets/a6656c00-4e3b-4db1-a8b0-3faecdbc700c)
