### ISSUE TITLE
Notpixel 

### ISSUE THREAD

**Issue by Bryanband85** [Solana0x/NotPixel#8]
Error when installing PIL (pillow) please help. I am using termux. Cannot run the script. No module PIL. Please help sir.

**Comment by Solana0x** [comment]
First install Python then ``` pip install -r requirements.txt```

**Comment by Bryanband85** [comment]
I did sir. But the same. Error. I found solution and it's done. Pillow installed. clang make \
    libjpeg-turbo before install pillow. Thank you sir. Thanks for the script.
