### ISSUE TITLE
userid expire

### ISSUE THREAD

**Issue by kashifrazzaq20** [Solana0x/NotPixel#9]
userid expire every 30 min what solution i only run on 1 session only

**Comment by kashifrazzaq20** [comment]
and how to decrease sleeping time

**Comment by ducquoa** [comment]
> and how to decrease sleeping time

you can decrease it in time_to_wait, you see (hours=1), change to 0.5 for 30 minutes for example

**Comment by kashifrazzaq20** [comment]
userid expire issue 
[11:12:46] Claiming resources
[11:12:46] DEAD :(

**Comment by Solana0x** [comment]
Add Query id again currently code doesnt re generated Query id on its own !

**Comment by kashifrazzaq20** [comment]
please do some thing bot is great but only query expire issue

**Comment by Solana0x** [comment]
working on that part
